export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS";
export const LOAD_GAME_SUCCESS = "LOAD_GAME_SUCCESS";
export const ADD_PLAYER_TO_GAME_SUCCESS = "ADD_PLAYER_TO_GAME_SUCCESS";
export const CREATE_PLAYER_SUCCESS = "CREATE_PLAYER_SUCCESS";
export const LOAD_PLAYER_SUCCESS = "LOAD_PLAYER_SUCCESS";
